### ISSUE TITLE
As a end-user I would see on-street BZ parking data on BZParking

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bz-parking-angular#11]
Data related to new "ParkingSensor" station type should also be visible on map on the list view. On the list view single sensor should be aggregated in relation to the attribute "group" (see metadata table). In other worlds, I expect to see a "virtual" ParkingStation called with the name of the group" area viale Druso" summing up the number of available spots, information provided by each sensor

- [x] modify parkingbz
- [x] change datacollector so it also provides municipality

**Comment by bertolla** [comment]
@rcavaliere 
I'm working on it, but wouldn't it be better if the sensor also shows me the capacity, even if it's always 1?

**Comment by rcavaliere** [comment]
No, this indication comes from the data provider. They would like to see this data in an aggregated form in the list of parking areas. The map should however provide the detail of each single sensor.

**Comment by bertolla** [comment]
We do not have a testing env for this app so I deployed to https://parking.bz.it directly. What do you think about it?

**Comment by rcavaliere** [comment]
Nice, for me it is OK to deploy directly on production.
A couple of things:
- [ ] I see now two times the city of Bolzano in the list of cities
- [ ] I don't see the data on the map, do you have to complete the implementation?

**Comment by bertolla** [comment]
Yes I' was about to fix it. Didn't expect you to check this thread so fast

**Comment by bertolla** [comment]
The problem of the municipality wrong should be fixed now and will be automatically fixed on the next station syn which is done once a day, so tomorrow.
For the map stuff I would suggest to rewrite this part so the data doesn't get fetched through geoserver but ninja gets used directly to avoid to rewrite queries which are already pretty complicated on geoserver.
If that is ok with you I would proceed like that.

**Comment by rcavaliere** [comment]
OK, would be a nice development so we can migrate from v1! go go go @bertolla!

**Comment by rcavaliere** [comment]
@bertolla I now see data on the map as well. Will it be possible, on the map only, that when you click on the area of the parking sensors, you can then see the locations of each single parking sensor? That would be nice!

**Comment by bertolla** [comment]
it could be done but you need to graphically make it understandable that this sensors are part of one and when they click on it that the data is of all 4 sensors. That's also the reason why I left only one point to display. Maybe a way could be to draw a polygon with the coordinates.

**Comment by rcavaliere** [comment]
I think that is not a big issue on the map, the aggregation need is stronger on the other view. If we have a clustering icon and then if you click on it you get the map with higher zoom and the positions of the single parking slots, that would be perfect for me.

**Comment by rcavaliere** [comment]
@bertolla, so what's next, do you think it is a big effort to add the localization view of each sensor on the map?

**Comment by bertolla** [comment]
I'm working on it. It's a bit tricky but should be done today
