### ISSUE TITLE
As a citizen of Bolzano I want to see only Bolzanos parking places by default, so I won't get confused and drive to Merano by mistake

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bz-parking-angular#3]
In this way, one can choose to view only the parking information he/she is looking for without the need to search through the whole list of parking areas.

**Comment by rcavaliere** [comment]
CBZ has asked to leave only Bolzano parking information as default. The other parking information can be seen through this button, but only if the user decides to activate it.

**Comment by bertolla** [comment]
The app is available to test here: http://bdp-test-env.b7twwguhvj.eu-west-1.elasticbeanstalk.com/parkingservice/

Pls test also with mobile.
Everybody can test; code review not necessary imao.

**Comment by ohnewein** [comment]
Tested in Chrome browser on a Ubuntu 17.04 system: works, but the UI with the 2 buttons dows not look very nice.

Tested on Android phone OnePlusX: On mobile the selection of the city is hidden in an icon. Good idea.

An idea could be to add two icons: One for Bolzano "BZ" and a second for Merano "ME". In this way the user does not to go into a submenu and can just toggle the cities he wants to see the parking lots from.

**Comment by rcavaliere** [comment]
I agree with @ohnewein. I would spend some more effort to improve the User Experience. I already shared the new app with the CBZ, and they like it.

**Comment by bertolla** [comment]
There are some things to consider:

1. The system works dynamically. So if in the future we will have Trento and other citys they will also be displayed on the site without any effort
2. If we want to use icons it gets really hard to get an icon for every city, town or hamlet
3. We are not really UI-Experts, nor Designer. Maybe we should create a new user-story and involve somebody with the know how (like Cima) and ask him to adapt the site.

**Comment by ohnewein** [comment]
We all agree that the UI is good enough.
