### ISSUE TITLE
As the major of the city of Bolzano I want to see the Substitute CBZ logo in the footer, so that I can show the site to my citizens

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bz-parking-angular#4]
Please use the following one
![1-1_citta_rgb](https://user-images.githubusercontent.com/9825179/35184115-9c277d4a-fdf1-11e7-8ccd-f89789c8a1d9.jpg)

**Comment by Piiit** [comment]
Tested on http://bdp-test-env.b7twwguhvj.eu-west-1.elasticbeanstalk.com/parkingservice/
It works

**Comment by rcavaliere** [comment]
For me it is OK. Please go into production
