### ISSUE TITLE
As a citizen of Bolzano, I have seen that the parking predictions are not shown anymore on BZParking. I would like to have to have this feature again since they are very useful to plan my trips by car.

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bz-parking-angular#7]

**Comment by bertolla** [comment]
can be tested on parking.bz.it

**Comment by Piiit** [comment]
@ohnewein @bertolla @rcavaliere Tested on mobile and desktop with Firefox. I can see predictions in form of a graph. 

Found (non-)issues: 
- `P07 - Mareccio` and `P13 - Direzional 2` have no predictions
- Predictions are shown only for a short period (4 hours), maybe we could show more <- new user story?
- Empty graphs have a wrong x-scala
- Some do not show a trend (no variance in prediction)

If that is known and accepted, I think the test succeeds.

**Comment by rcavaliere** [comment]
@Piiit this is OK, these 2 are parking areas which are currently in the system but are offline
